import React, { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Loader2 } from "lucide-react";

export default function PaymentTestLab() {
 const { user, loading } = useAuth(); const [search,setSearch]=useState(""); const [status,setStatus]=useState<"all"|"running"|"succeeded"|"failed">("all"); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [page,setPage]=useState(1); const [days,setDays]=useState(90);
 const filters={search:search||undefined,status:status==="all"?undefined:status,from:from||undefined,to:to||undefined};
 const runs=trpc.admin.paymentTestLabRuns.useQuery({...filters,page,pageSize:20}); const retention=trpc.admin.paymentTestLabRetention.useQuery(); const simulate=trpc.admin.runIpnSimulation.useMutation({onSuccess:()=>runs.refetch()}); const clean=trpc.admin.cleanupPaymentTestLabRuns.useMutation({onSuccess:()=>{retention.refetch();runs.refetch();}}); const update=trpc.admin.updatePaymentTestLabRetention.useMutation({onSuccess:()=>retention.refetch()});
 const exportCsv=trpc.admin.exportPaymentTestLabRunsCsv.useMutation({onSuccess:({filename,contentBase64})=>{const a=document.createElement("a");a.href=`data:text/csv;base64,${contentBase64}`;a.download=filename;a.click();}});
 if(loading)return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin"/></div>; if(!user||user.role!=="admin")return <div className="grid min-h-screen place-items-center"><Button onClick={startLogin}>Sign in as owner</Button></div>;
 return <DashboardLayout><main className="min-h-screen bg-[#f8f5f0] p-6"><div className="mx-auto max-w-3xl space-y-5"><header><p className="text-xs font-semibold uppercase tracking-widest text-[#a96346]">Owner only · payment test lab</p><h1 className="font-serif text-4xl">Signed IPN simulation</h1></header><Card><CardHeader><CardTitle>Audit retention</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Last cleanup: {retention.data?.lastCleanupAt?new Date(retention.data.lastCleanupAt).toLocaleString():"Not run yet"}{retention.data?.lastCleanupDeleted!=null?` · ${retention.data.lastCleanupDeleted} records deleted`:""}</p><div className="flex flex-wrap gap-2"><input aria-label="Retention days" type="number" min="7" max="3650" value={days} onChange={e=>setDays(Number(e.target.value))} className="w-28 rounded border p-2"/><Button variant="outline" onClick={()=>update.mutate({retentionDays:days})}>Save days</Button><Button variant="outline" onClick={()=>clean.mutate()} disabled={clean.isPending}>Run cleanup now</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Safe simulation</CardTitle></CardHeader><CardContent><Button onClick={()=>simulate.mutate({paymentStatus:"confirmed"})} disabled={simulate.isPending}>{simulate.isPending?"Running…":"Run signed confirmation test"}</Button></CardContent></Card><Card><CardHeader><CardTitle>Payment Test Lab history</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><input aria-label="Search payment test history" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search run ID" className="rounded border p-2"/><input aria-label="From date" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}} className="rounded border p-2"/><input aria-label="To date" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}} className="rounded border p-2"/><select aria-label="Payment test status" value={status} onChange={e=>{setStatus(e.target.value as typeof status);setPage(1)}} className="rounded border p-2"><option value="all">All statuses</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option><option value="running">Running</option></select><Button variant="outline" onClick={()=>exportCsv.mutate(filters)}>Export CSV</Button></div>{runs.data?.items.map(run=><div key={run.runId} className="flex justify-between rounded border p-3 text-sm"><code>{run.runId}</code><span>{run.status}</span></div>)}{!runs.data?.items.length&&<p className="text-sm text-muted-foreground">No matching payment test runs.</p>}<div className="flex justify-between"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} of {runs.data?.totalPages||0}</span><Button variant="outline" disabled={page>=(runs.data?.totalPages||1)} onClick={()=>setPage(page+1)}>Next</Button></div></CardContent></Card></div></main></DashboardLayout>;
}
