import React, { useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ShieldCheck } from "lucide-react";

type Locale = "en" | "ru" | "de" | "es";
const copy: Record<Locale, { back: string; eyebrow: string; title: string; intro: string; draft: string; sections: Array<{ title: string; body: string }> }> = {
  en: { back: "Back to the reading", eyebrow: "PRIVACY & DATA PROTECTION", title: "How we handle personal data", intro: "This notice explains what data is collected through this site, why it is used, who may process it, how long it is kept, and how to exercise applicable rights.", draft: "Working notice — replace the controller name, postal address and privacy contact before launch, and obtain local legal review for every target market.", sections: [
    { title: "1. Controller and contact", body: "The controller is the person or organisation operating Jyotish · by Anika. Controller name, postal address and a dedicated privacy contact must be inserted here before publication. Privacy requests should identify the request and the email used for the booking; we may ask for proportionate verification." },
    { title: "2. Data we collect", body: "Depending on the feature used, we may collect name, email address, birth date, exact birth time, birth city and country, selected language, selected service, interests or questions, payment and checkout identifiers, status-link tokens, delivery status, and technical security logs. Birth details can reveal information about an identifiable person and are treated as personal data. We ask users not to submit health, financial, government-ID or other highly sensitive information in the free-text field." },
    { title: "3. Purposes and legal bases", body: "We use booking and birth data to respond to a requested reading and perform the requested service; payment identifiers to create and verify checkout; email and delivery metadata to send receipts or reports; status tokens to show a limited order status; and security logs to protect the service and investigate abuse. The applicable basis may be contract performance, legal obligation, legitimate interest in security, or consent where consent is specifically requested. Optional analytics or marketing must be separately opt-in and must not be bundled with required booking consent." },
    { title: "4. Processors and recipients", body: "Service providers may process data on our instructions, including hosting/authentication, database and object storage, crypto-payment processing, transactional email, geocoding/time-zone lookup, and report-generation infrastructure. The exact provider list, locations, data-processing terms and international-transfer safeguards must be maintained by the operator and made available on request. We do not sell customer data." },
    { title: "5. Retention and deletion", body: "We keep data only as long as needed for the stated purpose, legal obligations, dispute handling and security. Receipt files are configured for a 24, 48 or 72-hour retention window; other booking/report records require an operator-defined retention schedule. Status links expire or can be revoked. Privacy-safe operational logs should be retained for the shortest period that supports security and reliability. Users may request deletion, subject to mandatory retention duties." },
    { title: "6. Rights and complaints", body: "Subject to applicable law, a person may request access, correction, deletion, restriction, portability where applicable, or object to certain processing, and may withdraw consent for future processing where consent is the basis. Contact the controller first; EU/EEA users may complain to their supervisory authority. Russian users may have additional rights and operator obligations under applicable Russian personal-data law." },
    { title: "7. Security and transfers", body: "The service uses access controls for owner tools, hashed status tokens, rate limits, PII masking in operational logs, encrypted transport where supported, and restricted storage references. No online service can guarantee absolute security. If data is transferred outside the user’s jurisdiction, the operator must document the applicable transfer mechanism and provider safeguards before processing." },
    { title: "8. Cookies and local storage", body: "The site may use essential browser storage to remember language, dashboard preferences and temporary interface state. Non-essential analytics or marketing technologies must be disclosed and activated only under the consent rules applicable to the visitor’s location. Browser settings can remove local storage, but this may reset preferences." },
    { title: "9. Astrology service disclaimer", body: "Astrology and numerology content is provided for personal reflection and spiritual exploration. It is not medical, legal, financial, psychological or other professional advice, does not guarantee predictions or outcomes, and does not limit mandatory consumer or data-protection rights." },
  ] },
  ru: { back: "Вернуться к заказу", eyebrow: "КОНФИДЕНЦИАЛЬНОСТЬ И ДАННЫЕ", title: "Как мы обрабатываем персональные данные", intro: "В этом уведомлении описано, какие данные собираются на сайте, зачем они используются, кто может их обрабатывать, как долго они хранятся и как реализовать применимые права.", draft: "Рабочий текст — до публикации укажите имя и адрес оператора, отдельный контакт по вопросам приватности и получите юридическую проверку для всех целевых рынков.", sections: [
    { title: "1. Оператор и контакт", body: "Оператором является лицо или организация, управляющая Jyotish · by Anika. До публикации необходимо указать имя оператора, почтовый адрес и специальный контакт по вопросам приватности. В запросе укажите суть требования и email, использованный при заказе; для защиты данных может потребоваться соразмерное подтверждение личности." },
    { title: "2. Какие данные мы собираем", body: "В зависимости от функции могут собираться имя, email, дата рождения, точное время рождения, город и страна рождения, выбранный язык, услуга, интересы или вопросы, идентификаторы оплаты и checkout, токены ссылок статуса, статусы доставки и технические журналы безопасности. Данные рождения относятся к персональным данным, если позволяют идентифицировать человека. Не указывайте в свободном поле сведения о здоровье, финансах, документах или иные особо чувствительные данные." },
    { title: "3. Цели и правовые основания", body: "Данные заказа и рождения используются для ответа на запрос и исполнения услуги; платежные идентификаторы — для создания и проверки checkout; email и данные доставки — для отправки квитанций и отчётов; токен статуса — для ограниченного показа состояния заказа; журналы — для безопасности и расследования злоупотреблений. В зависимости от ситуации основанием может быть исполнение договора, юридическая обязанность, законный интерес в безопасности или согласие, если оно запрашивается отдельно. Необязательная аналитика и маркетинг должны оформляться отдельным добровольным согласием." },
    { title: "4. Обработчики и получатели", body: "По поручению оператора данные могут обрабатывать провайдеры хостинга и авторизации, базы данных и объектного хранения, криптоплатежей, транзакционной почты, геокодирования и часовых поясов, а также генерации отчётов. Оператор обязан поддерживать актуальный перечень провайдеров, стран, договорных условий и гарантий трансграничной передачи. Данные клиентов не продаются." },
    { title: "5. Хранение и удаление", body: "Данные хранятся только столько, сколько необходимо для заявленной цели, юридических обязанностей, споров и безопасности. Файлы квитанций настроены на хранение 24, 48 или 72 часа; срок хранения заказов и отчётов должен быть отдельно установлен оператором. Ссылки статуса истекают или отзываются. Журналы должны храниться минимальный срок, достаточный для безопасности и надёжности. Удаление может быть ограничено обязательным хранением." },
    { title: "6. Права и жалобы", body: "В зависимости от применимого закона можно запросить доступ, исправление, удаление, ограничение обработки, переносимость в предусмотренных случаях, возразить против отдельных операций и отозвать согласие на будущее, если обработка основана на согласии. Сначала обратитесь к оператору; пользователям из ЕС/ЕЭЗ доступно обращение в надзорный орган. Для пользователей из России могут действовать дополнительные требования и обязанности оператора по российскому законодательству о персональных данных." },
    { title: "7. Безопасность и передачи", body: "Используются owner-only доступ к админке, хешированные токены статуса, rate limits, маскирование персональных данных в операционных логах, защищённый транспорт где поддерживается и хранение ссылок вместо лишних копий файлов. Абсолютная безопасность невозможна. Для передачи за пределы юрисдикции оператор должен заранее документировать правовой механизм и гарантии провайдера." },
    { title: "8. Cookies и localStorage", body: "Сайт может использовать обязательное browser-хранилище для языка, настроек админ-панели и временного состояния интерфейса. Необязательные аналитические или маркетинговые технологии должны быть раскрыты и включаться только при требуемом согласии. Очистка browser storage удалит настройки, но не обязательно удалит серверные данные." },
    { title: "9. Дисклеймер услуги", body: "Астрология и нумерология предоставляются для личной рефлексии и духовного исследования. Это не медицинская, юридическая, финансовая, психологическая или иная профессиональная консультация; результат и прогнозы не гарантируются. Дисклеймер не ограничивает обязательные права потребителей и требования законодательства о данных." },
  ] },
  de: { back: "Zurück zur Buchung", eyebrow: "DATENSCHUTZ", title: "Wie wir personenbezogene Daten verarbeiten", intro: "Diese Information erklärt, welche Daten diese Website erhebt, zu welchen Zwecken sie verwendet werden, wer sie verarbeiten kann, wie lange sie gespeichert werden und wie Rechte ausgeübt werden können.", draft: "Arbeitsfassung — vor Veröffentlichung Verantwortlichen, Anschrift und Datenschutzkontakt ergänzen und für alle Zielmärkte rechtlich prüfen lassen.", sections: [
    { title: "1. Verantwortlicher und Kontakt", body: "Verantwortlich ist die Person oder Organisation, die Jyotish · by Anika betreibt. Name, ladungsfähige Anschrift und ein Datenschutzkontakt müssen vor Veröffentlichung ergänzt werden. Anfragen sollten das Anliegen und die bei der Buchung verwendete E-Mail nennen; eine angemessene Identitätsprüfung kann erforderlich sein." },
    { title: "2. Erhobene Daten", body: "Je nach Funktion verarbeiten wir Name, E-Mail-Adresse, Geburtsdatum, genaue Geburtszeit, Geburtsort und -land, Sprache, gebuchte Leistung, Interessen oder Fragen, Zahlungs- und Checkout-Kennungen, Status-Link-Tokens, Zustellstatus und technische Sicherheitsprotokolle. Geburtsangaben sind personenbezogene Daten, wenn sie eine Person identifizierbar machen. Bitte keine Gesundheits-, Finanz-, Ausweis- oder sonstigen besonders sensiblen Daten in Freitextfeldern eingeben." },
    { title: "3. Zwecke und Rechtsgrundlagen", body: "Buchungs- und Geburtsdaten dienen der Bearbeitung und Vertragserfüllung; Zahlungskennungen der Checkout-Erstellung und -Prüfung; E-Mail- und Zustellmetadaten dem Versand von Belegen und Berichten; Status-Tokens einer begrenzten Statusanzeige; Sicherheitsprotokolle dem Schutz und der Missbrauchsaufklärung. Je nach Vorgang kommen Vertragserfüllung, gesetzliche Pflicht, berechtigtes Sicherheitsinteresse oder eine gesondert erteilte Einwilligung in Betracht. Optionale Analyse oder Werbung muss getrennt und freiwillig aktiviert werden." },
    { title: "4. Auftragsverarbeiter und Empfänger", body: "Auf Weisung können Hosting/Auth-, Datenbank- und Speicherdienste, Krypto-Zahlungsanbieter, Transaktionsmail, Geokodierung/Zeitzonen und Berichtsinfrastruktur Daten verarbeiten. Eine aktuelle Liste, Länder, Verträge und Garantien für internationale Übermittlungen müssen vom Betreiber gepflegt und auf Anfrage bereitgestellt werden. Kundendaten werden nicht verkauft." },
    { title: "5. Speicher- und Löschfristen", body: "Daten werden nur so lange aufbewahrt, wie Zweck, gesetzliche Pflichten, Streitfälle und Sicherheit es erfordern. Belegdateien haben eine konfigurierbare Frist von 24, 48 oder 72 Stunden; für Buchungen und Berichte ist eine eigene Frist festzulegen. Status-Links laufen ab oder können widerrufen werden. Protokolle sollen nur so lange wie für Sicherheit und Zuverlässigkeit nötig gespeichert werden." },
    { title: "6. Rechte und Beschwerden", body: "Nach anwendbarem Recht können Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und der Widerruf einer Einwilligung für die Zukunft verlangt werden. Wenden Sie sich zuerst an den Verantwortlichen; Personen im EWR können sich an eine Datenschutzaufsichtsbehörde wenden." },
    { title: "7. Sicherheit und Übermittlungen", body: "Wir verwenden owner-only Admin-Zugriff, gehashte Status-Tokens, Rate Limits, PII-Maskierung in Betriebslogs, geschützte Übertragung soweit unterstützt und Speicherreferenzen statt unnötiger Dateikopien. Absolute Sicherheit kann nicht garantiert werden. Für Übermittlungen außerhalb der Jurisdiktion sind Rechtsgrundlage und Schutzmaßnahmen vorab zu dokumentieren." },
    { title: "8. Cookies und localStorage", body: "Essentielle Browser-Speicherung kann Sprache, Admin-Einstellungen und temporären UI-Zustand merken. Nicht essentielle Analyse- oder Marketingtechnologien dürfen nur nach der erforderlichen Einwilligung aktiviert werden. Das Löschen des Browser-Speichers setzt Präferenzen zurück, löscht aber nicht automatisch Serverdaten." },
    { title: "9. Hinweis zum Angebot", body: "Astrologie und Numerologie dienen der persönlichen Reflexion und spirituellen Erkundung. Sie sind keine medizinische, rechtliche, finanzielle, psychologische oder sonstige professionelle Beratung und garantieren keine Ergebnisse. Zwingende Verbraucher- und Datenschutzrechte bleiben unberührt." },
  ] },
  es: { back: "Volver a la reserva", eyebrow: "PRIVACIDAD Y DATOS", title: "Cómo tratamos los datos personales", intro: "Este aviso explica qué datos recoge el sitio, para qué se utilizan, quién puede tratarlos, cuánto tiempo se conservan y cómo ejercer los derechos aplicables.", draft: "Texto de trabajo — antes de publicar, complete el responsable, domicilio y contacto de privacidad y solicite revisión jurídica para cada mercado objetivo.", sections: [
    { title: "1. Responsable y contacto", body: "El responsable es la persona u organización que opera Jyotish · by Anika. Antes de publicar deben añadirse su nombre, domicilio y un contacto específico de privacidad. Las solicitudes deben indicar el asunto y el email utilizado en la reserva; puede ser necesaria una verificación proporcionada." },
    { title: "2. Datos que recogemos", body: "Según la función, podemos tratar nombre, email, fecha y hora exactas de nacimiento, ciudad y país de nacimiento, idioma, servicio elegido, intereses o preguntas, identificadores de pago y checkout, tokens de estado, estado de entrega y registros técnicos de seguridad. Los datos de nacimiento son personales cuando permiten identificar a alguien. No introduzca datos de salud, financieros, documentos oficiales u otros datos especialmente sensibles en campos libres." },
    { title: "3. Finalidades y bases jurídicas", body: "Usamos los datos de reserva y nacimiento para responder y prestar el servicio; los identificadores de pago para crear y verificar el checkout; los datos de email y entrega para enviar recibos o informes; los tokens para mostrar un estado limitado; y los registros para seguridad y prevención del abuso. Según el caso, la base puede ser la ejecución de un contrato, una obligación legal, el interés legítimo de seguridad o un consentimiento separado. La analítica o el marketing opcionales deben ser voluntarios y separados." },
    { title: "4. Encargados y destinatarios", body: "Proveedores de hosting/autenticación, base de datos y almacenamiento, pagos cripto, correo transaccional, geocodificación/zona horaria e infraestructura de informes pueden tratar datos siguiendo instrucciones del responsable. El operador debe mantener la lista de proveedores, países, contratos y garantías de transferencias internacionales. No vendemos datos de clientes." },
    { title: "5. Conservación y eliminación", body: "Conservamos los datos solo durante el tiempo necesario para la finalidad, obligaciones legales, conflictos y seguridad. Los recibos tienen una retención configurable de 24, 48 o 72 horas; las reservas e informes requieren un plazo definido por el operador. Los enlaces de estado caducan o pueden revocarse. Los registros deben conservarse el mínimo necesario para seguridad y fiabilidad." },
    { title: "6. Derechos y reclamaciones", body: "Según la ley aplicable, puede solicitar acceso, rectificación, supresión, limitación, portabilidad cuando corresponda, oponerse a ciertos tratamientos y retirar el consentimiento para el futuro cuando esa sea la base. Contacte primero con el responsable; las personas del EEE pueden acudir a su autoridad de protección de datos." },
    { title: "7. Seguridad y transferencias", body: "Usamos acceso owner-only para la administración, tokens de estado hash, límites de frecuencia, enmascaramiento de PII en logs, transporte protegido cuando está disponible y referencias de almacenamiento. Ningún servicio puede garantizar seguridad absoluta. Las transferencias internacionales deben documentar previamente su mecanismo jurídico y garantías." },
    { title: "8. Cookies y localStorage", body: "El almacenamiento esencial del navegador puede recordar idioma, preferencias del panel y estado temporal de la interfaz. Las tecnologías no esenciales de analítica o marketing solo deben activarse con el consentimiento exigido. Borrar el almacenamiento restablece preferencias, pero no elimina automáticamente los datos del servidor." },
    { title: "9. Aviso sobre el servicio", body: "La astrología y la numerología se ofrecen para reflexión personal y exploración espiritual. No constituyen asesoramiento médico, legal, financiero, psicológico ni profesional, y no garantizan predicciones o resultados. Se mantienen intactos los derechos imperativos de consumidores y protección de datos." },
  ] },
};

export default function Privacy() {
  const [locale, setLocale] = useState<Locale>(() => { const value = window.localStorage.getItem("public-locale"); return value === "ru" || value === "de" || value === "es" ? value : "en"; });
  const t = copy[locale];
  return <main className="min-h-screen bg-[#f8f5f0] px-5 py-8 text-[#2f2923] sm:px-8 lg:px-16"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-center justify-between gap-4"><Link href="/" className="inline-flex items-center gap-2 text-sm text-[#8f4e36] hover:underline"><ArrowLeft size={16} />{t.back}</Link><select aria-label="Language" value={locale} onChange={(event) => { const next = event.target.value as Locale; setLocale(next); window.localStorage.setItem("public-locale", next); }} className="rounded-full border border-[#d8c8bd] bg-white px-3 py-2 text-sm"><option value="en">EN</option><option value="ru">RU</option><option value="de">DE</option><option value="es">ES</option></select></div><div className="mt-16"><p className="text-xs font-semibold tracking-[0.24em] text-[#aa6245]">{t.eyebrow}</p><h1 className="mt-3 max-w-3xl font-serif text-4xl leading-tight sm:text-6xl">{t.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#635a52]">{t.intro}</p><div className="mt-6 flex gap-3 rounded-2xl border border-[#d9a441]/40 bg-[#fff8e8] p-4 text-sm leading-6 text-[#635a52]"><ShieldCheck className="mt-1 shrink-0 text-[#aa6245]" size={20} /><p>{t.draft}</p></div></div><div className="mt-12 space-y-8">{t.sections.map((section) => <section key={section.title} className="rounded-2xl border border-[#eadfd7] bg-white p-6 shadow-sm sm:p-8"><h2 className="font-serif text-2xl">{section.title}</h2><p className="mt-3 leading-7 text-[#635a52]">{section.body}</p></section>)}</div><p className="mt-10 text-xs leading-6 text-[#806f64]">This page is a working information notice, not legal advice. The operator remains responsible for selecting the correct controller, legal bases, retention periods, provider agreements, transfer mechanisms, records and local filings.</p></div></main>;
}
