import React from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileText, Loader2, Play, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function ReportStudio() {
  const [selectedJobId, setSelectedJobId] = useState<number | null>(null);
  const [latitude, setLatitude] = useState("0");
  const [longitude, setLongitude] = useState("0");
  const [timezone, setTimezone] = useState("UTC");
  const [offset, setOffset] = useState("0");
  const [summary, setSummary] = useState("");
  const queue = trpc.reportStudio.queue.useQuery();
  const detail = trpc.reportStudio.getJob.useQuery({ reportJobId: selectedJobId ?? 0 }, { enabled: selectedJobId !== null });
  const utils = trpc.useUtils();
  const runCalculation = trpc.reportStudio.runCalculation.useMutation({ onSuccess: () => { toast.success("PDF preview is ready for owner review."); void utils.reportStudio.queue.invalidate(); void detail.refetch(); }, onError: (error) => toast.error(error.message) });
  const approve = trpc.reportStudio.approve.useMutation({ onSuccess: () => { toast.success("Report approved. It is ready for controlled delivery."); void utils.reportStudio.queue.invalidate(); void detail.refetch(); }, onError: (error) => toast.error(error.message) });
  const selectedVersion = detail.data?.versions?.[0];
  const previewUrl = selectedVersion?.pdfStorageKey ? `/manus-storage/${selectedVersion.pdfStorageKey}` : null;

  return <DashboardLayout><main className="min-h-screen bg-[#f8f5f0] px-4 py-6 text-[#28231f] sm:px-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#a96346]">Report Studio · owner only</p><h1 className="mt-2 font-serif text-4xl">Review & approve reports</h1><p className="mt-2 max-w-2xl text-sm text-[#635a52]">Verified payments create a queued job. Resolve birth location, run the deterministic calculation, inspect the PDF preview, then approve it before any client delivery.</p></div><Link href="/admin"><Button variant="outline">Back to admin</Button></Link></div>
    {queue.error ? <Card className="border-red-200 bg-red-50"><CardContent className="p-5 text-sm text-red-800">This workspace is restricted to the account owner. {queue.error.message}</CardContent></Card> : <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText size={18}/>Report queue</CardTitle></CardHeader><CardContent className="space-y-2">{queue.isLoading ? <div className="flex items-center gap-2 text-sm text-[#635a52]"><Loader2 className="animate-spin" size={16}/>Loading…</div> : !queue.data?.length ? <p className="text-sm text-[#635a52]">No paid report jobs yet.</p> : queue.data.map(({ job, version }) => <button key={job.id} type="button" onClick={() => setSelectedJobId(job.id)} className={`w-full rounded-xl border p-3 text-left transition ${selectedJobId === job.id ? "border-[#a96346] bg-[#fbf6ec]" : "border-[#28231f]/10 bg-white hover:border-[#a96346]/50"}`}><div className="flex items-center justify-between gap-2"><span className="font-semibold">#{job.id} · booking #{job.bookingId}</span><span className="rounded-full bg-[#efe4d5] px-2 py-1 text-[10px] font-bold uppercase">{version?.status ?? job.status}</span></div><p className="mt-1 text-xs text-[#635a52]">{job.packageType} · {job.language} · attempt {job.attemptCount}</p>{job.lastErrorMessage && <p className="mt-2 text-xs text-red-700">{job.lastErrorMessage}</p>}</button>)}</CardContent></Card>
      <div className="space-y-6">{!selectedJobId || !detail.data ? <Card><CardContent className="p-8 text-sm text-[#635a52]">Select a paid report job to begin review.</CardContent></Card> : <><Card><CardHeader><CardTitle>Calculation input confirmation</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-[#635a52]">Client: <strong>{detail.data.booking?.name}</strong> · {detail.data.booking?.birthDate} {detail.data.booking?.birthTime} · {detail.data.booking?.birthCity}, {detail.data.booking?.birthCountry}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor="latitude">Latitude</Label><Input id="latitude" value={latitude} onChange={(e) => setLatitude(e.target.value)} type="number" step="0.000001" /></div><div><Label htmlFor="longitude">Longitude</Label><Input id="longitude" value={longitude} onChange={(e) => setLongitude(e.target.value)} type="number" step="0.000001" /></div><div><Label htmlFor="timezone">IANA timezone</Label><Input id="timezone" value={timezone} onChange={(e) => setTimezone(e.target.value)} placeholder="Europe/Berlin" /></div><div><Label htmlFor="offset">UTC offset minutes</Label><Input id="offset" value={offset} onChange={(e) => setOffset(e.target.value)} type="number" step="1" /></div></div><Button className="mt-5 bg-[#a96346] text-white hover:bg-[#8f5037]" onClick={() => runCalculation.mutate({ reportJobId: selectedJobId, latitude: Number(latitude), longitude: Number(longitude), timezone, timeZoneOffsetMinutes: Number(offset) })} disabled={runCalculation.isPending}><Play size={16}/>{runCalculation.isPending ? "Calculating…" : "Run calculation & render preview"}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck size={18}/>Owner review</CardTitle></CardHeader><CardContent>{previewUrl ? <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><iframe title="Report PDF preview" src={previewUrl} className="h-[720px] w-full rounded-xl border border-[#28231f]/15 bg-white"/><div className="space-y-4"><div className="rounded-xl bg-[#fbf6ec] p-4 text-sm"><p className="font-semibold">Version {selectedVersion?.versionNumber} · {selectedVersion?.status}</p><p className="mt-2 text-[#635a52]">Facts status: {detail.data.calculation?.validationStatus ?? "not calculated"}</p></div><div><Label htmlFor="summary">Approval note</Label><textarea id="summary" value={summary} onChange={(e) => setSummary(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border border-[#28231f]/15 bg-white p-3 text-sm" placeholder="Optional owner review note"/></div><Button className="w-full bg-[#28231f] text-white hover:bg-[#403830]" onClick={() => approve.mutate({ reportJobId: selectedJobId, versionId: selectedVersion!.id, summary })} disabled={approve.isPending || selectedVersion?.status === "approved"}>{approve.isPending ? "Approving…" : selectedVersion?.status === "approved" ? <><CheckCircle2 size={16}/>Approved</> : "Approve PDF for delivery"}</Button></div></div> : <p className="text-sm text-[#635a52]">No PDF preview has been rendered for this job. Run the calculation after confirming the birth location and timezone.</p>}</CardContent></Card></>}</div>
    </div>}</div></main></DashboardLayout>;
}
