import React, { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, PackageCheck, PackagePlus, PackageX, Pencil, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

type PackageType = "basic" | "basic_plus";
type ServicePackage = { id: number; code: PackageType; version: number; packageType: PackageType; nameEn: string; nameRu: string; nameDe: string; nameEs: string; active: boolean };
type PackageDraft = { mode: "create" | "edit"; id?: number; packageType: PackageType; nameEn: string; nameRu: string; nameDe: string; nameEs: string; active: boolean };

function isRussianAdmin() { return typeof window !== "undefined" && window.localStorage.getItem("admin-locale") === "ru"; }
function draftFrom(row: ServicePackage, mode: PackageDraft["mode"]): PackageDraft { return { mode, ...(mode === "edit" ? { id: row.id } : {}), packageType: row.packageType ?? row.code, nameEn: row.nameEn, nameRu: row.nameRu, nameDe: row.nameDe, nameEs: row.nameEs, active: mode === "create" ? true : row.active }; }
const EMPTY_DRAFT: PackageDraft = { mode: "create", packageType: "basic", nameEn: "", nameRu: "", nameDe: "", nameEs: "", active: true };

export default function ServicePackages() {
  const { user, loading } = useAuth();
  const russian = isRussianAdmin();
  const copy = russian
    ? { eyebrow: "Только для владельца", title: "Версии пакетов услуг", body: "Создавайте и редактируйте будущие версии пакетов. Новые заказы получают актуальную активную версию; исторические снимки стоимости и состав заказа не меняются.", back: "Назад в админ-панель", active: "Активен", inactive: "Неактивен", deactivate: "Отключить", activate: "Включить", confirmTitle: "Подтвердить изменение пакета", confirmBody: "Новые клиенты больше не смогут выбрать отключённый пакет. Как минимум один пакет всегда останется активным.", cancel: "Отмена", confirm: "Подтвердить", restricted: "Этот экран доступен только владельцу.", signIn: "Войти как владелец", loading: "Загрузка пакетов…", packageVersion: "Версия", updated: "Состояние пакета обновлено.", updateFailed: "Не удалось изменить состояние пакета.", create: "Создать версию", edit: "Редактировать", newVersion: "Новая версия", formCreate: "Создание версии пакета", formEdit: "Редактирование версии пакета", packageType: "Тип пакета", basic: "Базовый", basicPlus: "Базовый + нумерология", activeNext: "Сделать активной версией", nameEn: "Название (English)", nameRu: "Название (Русский)", nameDe: "Название (Deutsch)", nameEs: "Название (Español)", save: "Сохранить версию", saving: "Сохранение…", saved: "Версия пакета сохранена.", formHint: "Активация версии автоматически отключает другие версии того же типа. Как минимум один пакет на сайте остаётся активным." }
    : { eyebrow: "Owner only", title: "Service package versions", body: "Create and edit future package versions. New bookings use the current active version; historical price snapshots and booked contents never change.", back: "Back to admin", active: "Active", inactive: "Inactive", deactivate: "Deactivate", activate: "Activate", confirmTitle: "Confirm package change", confirmBody: "New customers will no longer be able to select a deactivated package. At least one package always remains active.", cancel: "Cancel", confirm: "Confirm", restricted: "This screen is restricted to the account owner.", signIn: "Sign in as owner", loading: "Loading packages…", packageVersion: "Version", updated: "Package state updated.", updateFailed: "Could not update the package state.", create: "Create version", edit: "Edit", newVersion: "New version", formCreate: "Create package version", formEdit: "Edit package version", packageType: "Package type", basic: "Basic", basicPlus: "Basic + numerology", activeNext: "Make this the active version", nameEn: "Name (English)", nameRu: "Name (Russian)", nameDe: "Name (German)", nameEs: "Name (Spanish)", save: "Save version", saving: "Saving…", saved: "Package version saved.", formHint: "Activating a version deactivates other versions of the same package type. At least one site package remains active." };
  const [pending, setPending] = useState<ServicePackage | null>(null);
  const [draft, setDraft] = useState<PackageDraft | null>(null);
  const packages = trpc.admin.servicePackages.useQuery(undefined, { enabled: user?.role === "admin", retry: false });
  const utils = trpc.useUtils();
  const refreshCatalog = () => { void utils.admin.servicePackages.invalidate(); void utils.pricing.packages.invalidate(); };
  const updateActive = trpc.admin.updateServicePackageActive.useMutation({ onSuccess: () => { setPending(null); refreshCatalog(); toast.success(copy.updated); }, onError: (error) => { setPending(null); toast.error(error.message || copy.updateFailed); } });
  const createVersion = trpc.admin.createServicePackageVersion.useMutation({ onSuccess: () => { setDraft(null); refreshCatalog(); toast.success(copy.saved); }, onError: (error) => toast.error(error.message || copy.updateFailed) });
  const updateVersion = trpc.admin.updateServicePackageVersion.useMutation({ onSuccess: () => { setDraft(null); refreshCatalog(); toast.success(copy.saved); }, onError: (error) => toast.error(error.message || copy.updateFailed) });
  const activeCount = (packages.data ?? []).filter((entry) => entry.active).length;
  const saving = createVersion.isPending || updateVersion.isPending;
  const updateDraft = <K extends keyof PackageDraft>(key: K, value: PackageDraft[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const submitDraft = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!draft) return; const { mode, id, ...data } = draft; if (mode === "create") createVersion.mutate(data); else if (id) updateVersion.mutate({ id, nameEn: data.nameEn, nameRu: data.nameRu, nameDe: data.nameDe, nameEs: data.nameEs, active: data.active }); };

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f8f5f0] text-[#635a52]"><Loader2 className="animate-spin" /></div>;
  if (!user || user.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#f8f5f0] px-6 text-center text-[#28231f]"><div><h1 className="font-serif text-4xl">{copy.restricted}</h1><button type="button" onClick={() => startLogin()} className="mt-6 rounded-full bg-[#28231f] px-5 py-3 font-semibold text-[#fffaf4]">{copy.signIn}</button></div></div>;

  return <DashboardLayout><main className="min-h-screen bg-[#f8f5f0] px-4 py-6 text-[#28231f] sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#28231f]/10 pb-6"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#b55b39]">{copy.eyebrow}</p><h1 className="mt-2 font-serif text-4xl tracking-[-0.03em]">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#635a52]">{copy.body}</p></div><div className="flex gap-2"><Button type="button" onClick={() => setDraft(EMPTY_DRAFT)}><PackagePlus size={16} />{copy.create}</Button><Link href="/admin"><Button variant="outline">{copy.back}</Button></Link></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">{packages.isLoading ? <div className="col-span-full flex items-center gap-2 text-sm text-[#635a52]"><Loader2 size={16} className="animate-spin" />{copy.loading}</div> : packages.error ? <Card className="col-span-full border-red-200 bg-red-50"><CardContent className="p-5 text-sm text-red-800">{packages.error.message}</CardContent></Card> : packages.data?.map((entry) => { const row = entry as ServicePackage; const localizedName = russian ? row.nameRu : row.nameEn; const disablingLastPackage = row.active && activeCount <= 1; return <Card key={`${row.code}-${row.version}`} className={row.active ? "border-emerald-200 bg-[#fffaf4]" : "border-[#28231f]/10 bg-[#f2eee8] opacity-85"}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="font-serif text-2xl">{localizedName}</CardTitle><p className="mt-1 text-xs text-[#635a52]">{row.code} · {copy.packageVersion} {row.version}</p></div><Badge className={row.active ? "bg-emerald-100 text-emerald-800 hover:bg-emerald-100" : "bg-slate-200 text-slate-700 hover:bg-slate-200"}>{row.active ? <PackageCheck size={13} className="mr-1" /> : <PackageX size={13} className="mr-1" />}{row.active ? copy.active : copy.inactive}</Badge></div></CardHeader><CardContent><p className="flex items-start gap-2 text-xs leading-5 text-[#635a52]"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[#b55b39]" />{row.active ? copy.body : copy.inactive}</p><div className="mt-5 grid grid-cols-2 gap-2"><Button type="button" size="sm" variant="outline" onClick={() => setDraft(draftFrom(row, "edit"))}><Pencil size={14} />{copy.edit}</Button><Button type="button" size="sm" variant="outline" onClick={() => setDraft(draftFrom(row, "create"))}><PackagePlus size={14} />{copy.newVersion}</Button></div><Button type="button" variant={row.active ? "outline" : "default"} className="mt-2 w-full" disabled={updateActive.isPending || disablingLastPackage} onClick={() => setPending(row)}>{row.active ? copy.deactivate : copy.activate}</Button>{disablingLastPackage && <p className="mt-2 text-center text-[11px] text-[#8d6d1f]">{copy.confirmBody}</p>}</CardContent></Card>; })}</div>
    {draft && <Card className="mt-6 border-[#b55b39]/30 bg-[#fffaf4]"><CardHeader><h2 className="font-serif text-2xl">{draft.mode === "create" ? copy.formCreate : copy.formEdit}</h2><p className="text-xs leading-5 text-[#635a52]">{copy.formHint}</p></CardHeader><CardContent><form className="grid gap-4" onSubmit={submitDraft}><label className="text-sm font-semibold">{copy.packageType}<select value={draft.packageType} disabled={draft.mode === "edit"} onChange={(event) => updateDraft("packageType", event.target.value as PackageType)} className="mt-1 block w-full rounded-xl border border-[#28231f]/15 bg-white px-3 py-2 text-sm"><option value="basic">{copy.basic}</option><option value="basic_plus">{copy.basicPlus}</option></select></label><div className="grid gap-3 sm:grid-cols-2">{(["nameEn", "nameRu", "nameDe", "nameEs"] as const).map((field) => <label key={field} className="text-sm font-semibold">{copy[field]}<input required minLength={2} maxLength={160} value={draft[field]} onChange={(event) => updateDraft(field, event.target.value)} className="mt-1 block w-full rounded-xl border border-[#28231f]/15 bg-white px-3 py-2 text-sm" /></label>)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.active} onChange={(event) => updateDraft("active", event.target.checked)} />{copy.activeNext}</label><div className="flex flex-wrap gap-2"><Button type="submit" disabled={saving}>{saving ? <><Loader2 size={16} className="animate-spin" />{copy.saving}</> : copy.save}</Button><Button type="button" variant="outline" onClick={() => setDraft(null)}>{copy.cancel}</Button></div></form></CardContent></Card>}</div></main><AlertDialog open={Boolean(pending)} onOpenChange={(open) => { if (!open) setPending(null); }}><AlertDialogContent className="bg-[#fffaf4]"><AlertDialogHeader><AlertDialogTitle>{copy.confirmTitle}</AlertDialogTitle><AlertDialogDescription>{copy.confirmBody}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{copy.cancel}</AlertDialogCancel><AlertDialogAction onClick={() => pending && updateActive.mutate({ code: pending.code, version: pending.version, active: !pending.active })}>{copy.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></DashboardLayout>;
}
