export type Locale = "en" | "ru";

export const COPY = {
  en: {
    localeLabel: "Language", questionsLabel: "Questions", questionsTitle: "Before you book", footerBody: "A thoughtful reading of your inner sky.", footerNote: "Interpretive practice for reflection", navReading: "The reading", navHow: "How it works", navFaq: "FAQ", book: "Book a reading", badge: "Vedic astrology · Jyotish",
    heroTitle: "A clearer map for your inner sky.", heroBody: "A personalized Vedic birth chart reading, prepared with care and delivered as a detailed multi-page PDF for reflection, self-understanding, and spiritual exploration.", features: ["4 languages", "Multi-page PDF", "Personal & structured"], rasiChart: "Rasi chart", patternTitle: "Read the patterns.", patternBody: "A grounded interpretation of the symbols, houses, and planetary placements that shape your chart.", basicLabel: "basic reading", begin: "Begin your reading", explore: "Explore the reading", offering: "The offering", offeringTitle: "A reading made to be returned to.", offeringBody: "Your chart is translated into a calm, readable document — something you can sit with, revisit, and use as a prompt for reflection.",
    basicTitle: "Basic Vedic chart reading", basicBody: "A personal Jyotish natal chart interpretation, focused on key planetary placements, houses, strengths, tendencies, and areas for reflection.", optional: "Optional add-on", addOn: "Indian numerology & traditional symbols", addOnBody: "Numerology overview, traditionally associated favorable and challenging days and numbers, plus traditional gemstone suggestions.",
    process: "The process", processTitle: "Simple to begin. Thoughtful in delivery.", steps: [{ title: "Share your birth details", text: "Provide your place of birth, date of birth, and exact time of birth. These details shape the accuracy and completeness of the chart interpretation." }, { title: "Receive your reading", text: "Your personalized interpretation is prepared as a detailed, multi-page PDF document in your preferred language." }, { title: "Return to the insight", text: "Read at your own pace and ask one round of clarification questions about the delivered document." }],
    bookSection: "Book your reading", bookTitle: "Bring the right details.", bookBody: "The city, country, date, and exact time of birth are required. The more accurate the information, the more precise and complete the chart interpretation can be.", name: "Preferred name", email: "Email", date: "Date of birth", time: "Exact time of birth", city: "City of birth", country: "Country of birth", language: "Preferred language", interest: "What would you like to reflect on?", request: "Request my reading", optionalInterest: "Optional: themes, questions, or areas of interest", placeholderName: "Your name", placeholderCity: "City", placeholderCountry: "Country", pdfReading: "PDF reading", requestReading: "Request a reading", birthDetails: "Your birth details", noteHeading: "A note on the practice.", faqs: [{ question: "What details do I need to provide?", answer: "Please provide your place of birth (city and country), date of birth, and exact time of birth. The accuracy and completeness of the reading depend on the correctness of these details." }, { question: "What will I receive?", answer: "You will receive a detailed, multi-page PDF document with the main themes of your Vedic natal chart explained in clear language." }, { question: "What is included in the $10 add-on?", answer: "The add-on includes an Indian numerology overview, traditionally associated favorable and challenging days and numbers, and traditional gemstone suggestions." }, { question: "Is this medical, legal, or financial advice?", answer: "No. Astrology and numerology are interpretive practices for reflection and spiritual exploration. They are not a substitute for qualified professional advice." }], note: "Astrology and numerology are interpretive practices for reflection and spiritual exploration, not medical, legal, financial, psychological, or professional advice.", successTitle: "Your request is received.", continueCheckout: "Continue to crypto checkout", anotherRequest: "Send another request", privacy: "Your details are used only to prepare and respond to your reading request. Payment is processed securely by NOWPayments; the site does not store wallet private keys.",
  },
  ru: {
    localeLabel: "Язык", questionsLabel: "Вопросы", questionsTitle: "Перед заказом", footerBody: "Вдумчивое чтение вашего внутреннего неба.", footerNote: "Интерпретативная практика для размышления", navReading: "О чтении", navHow: "Как это работает", navFaq: "Вопросы", book: "Заказать чтение", badge: "Ведическая астрология · Джйотиш",
    heroTitle: "Более ясная карта вашего внутреннего неба.", heroBody: "Персональное чтение ведической натальной карты, подготовленное бережно и оформленное в подробный многостраничный PDF для самопонимания и духовного исследования.", features: ["4 языка", "Многостраничный PDF", "Лично и структурированно"], rasiChart: "Карта Раши", patternTitle: "Читайте закономерности.", patternBody: "Взвешенная интерпретация символов, домов и положений планет вашей карты.", basicLabel: "базовое чтение", begin: "Начать чтение", explore: "Подробнее об услуге", offering: "Услуга", offeringTitle: "К чтению хочется возвращаться.", offeringBody: "Ваша карта превращается в спокойный, понятный документ, к которому можно возвращаться и использовать его для размышлений.",
    basicTitle: "Базовое чтение ведической карты", basicBody: "Персональная интерпретация натальной карты в традиции Джйотиш: положения планет, дома, сильные стороны, склонности и темы для размышления.", optional: "Дополнительно", addOn: "Индийская нумерология и традиционные символы", addOnBody: "Обзор нумерологии, традиционно благоприятных и сложных дней и чисел, а также рекомендации по камням.",
    process: "Процесс", processTitle: "Начать просто. Результат — продуманный.", steps: [{ title: "Передайте данные рождения", text: "Укажите место, дату и точное время рождения. Эти данные влияют на точность и полноту интерпретации карты." }, { title: "Получите чтение", text: "Персональная интерпретация будет подготовлена в виде подробного многостраничного PDF на выбранном языке." }, { title: "Возвращайтесь к инсайтам", text: "Читайте в удобном темпе и задайте один раунд уточняющих вопросов по готовому документу." }],
    bookSection: "Заказать чтение", bookTitle: "Укажите точные данные.", bookBody: "Необходимы город, страна, дата и точное время рождения. Чем точнее данные, тем полнее и точнее интерпретация натальной карты.", name: "Имя", email: "Email", date: "Дата рождения", time: "Точное время рождения", city: "Город рождения", country: "Страна рождения", language: "Язык чтения", interest: "На что вы хотели бы обратить внимание?", request: "Заказать чтение", optionalInterest: "Необязательно: темы, вопросы или интересующие области", placeholderName: "Ваше имя", placeholderCity: "Город", placeholderCountry: "Страна", pdfReading: "Чтение в PDF", requestReading: "Заказать чтение", birthDetails: "Данные рождения", noteHeading: "Важно знать.", faqs: [{ question: "Какие данные нужно предоставить?", answer: "Укажите место рождения (город и страну), дату и точное время рождения. Точность и полнота чтения зависят от корректности этих данных." }, { question: "Что я получу?", answer: "Вы получите подробный многостраничный PDF с основными темами вашей ведической натальной карты, изложенными понятным языком." }, { question: "Что входит в дополнение за $10?", answer: "Дополнение включает обзор индийской нумерологии, традиционно благоприятных и сложных дней и чисел, а также рекомендации по камням." }, { question: "Это медицинская, юридическая или финансовая консультация?", answer: "Нет. Астрология и нумерология — интерпретативные практики для размышления и духовного исследования, а не замена профессиональной консультации." }], note: "Астрология и нумерология являются интерпретативными практиками для размышления и духовного исследования, а не медицинской, юридической, финансовой, психологической или профессиональной консультацией.", successTitle: "Заявка получена.", continueCheckout: "Перейти к криптооплате", anotherRequest: "Отправить ещё одну заявку", privacy: "Ваши данные используются только для подготовки и обработки запроса на чтение. Платёж безопасно обрабатывается NOWPayments; сайт не хранит приватные ключи кошелька.",
  },
} as const;
